config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :staffs
    end
  end

  devise_for :users, skip: [:registration, :sessions, :password]
  devise_scope :user do
    authenticated :user do
      root to: "statics#landing", as: "authenticated_root"
    end


    authenticated :user, lambda {|user| user.userable_type == "Staff" && user.userable.role == "Administrator"} do
      resources :staffs
    end

    unauthenticated do
      root to: "devise/sessions#new"
      post "/" => "devise/sessions#create", as: :user_session
    end
    delete "sign_out" => "devise/sessions#destroy", as: :destroy_user_session
  end

  get "*unmatched_routes", to: "application#raise_not_found!", via: :all
  post "*unmatched_routes", to: "application#raise_not_found!", via: :all
  put "*unmatched_routes", to: "application#raise_not_found!", via: :all
  delete "*unmatched_routes", to: "application#raise_not_found!", via: :all
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_one :user, as: :userable
  accepts_nested_attributes_for :user

  validates :first_name, presence: true
  validates :sex, presence: true, inclusion: { in: SEX}
  validates :role, presence: true, inclusion: { in: ROLE}
  validates_associated :user

  scope :by_full_name, ->(contex) { where{(first_name =~ "%#{contex}") | (last_name =~ "%#{contex}")}}
  scope :by_gender, ->(gender) { where{sex == gender.humanize}}

  def display_name
    return "#{self.front_title}. #{full_name}" if self.front_title.present? && !self.back_title.present?
    return "#{full_name}, #{self.back_title}" if !self.front_title.present? && self.back_title.present?
    return "#{self.front_title}. #{full_name}, #{self.back_title}" if self.front_title.present? && self.back_title.present?
    return full_name
  end


  private

    def full_name
      return "#{self.first_name} #{self.last_name}" if self.last_name.present?
      return self.first_name
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]
  validates :username, presence: true, uniqueness: true

  belongs_to :userable, polymorphic: true

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end
end

app/controllers/api/v1/staffs_controller.rb
class Api::V1::StaffsController < ApiController
  respond_to :json

  def index
    @presenter = Api::V1::Staffs::Index.new(params)
  end

  def show
    @staff = Staff.includes(:user).find(params[:id])
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session
  rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found

  def render_not_found(e)
    respond_to do |format|
      format.html { render template: "errors/404", status: 404}
      format.json { render json: {messages: "The resource you're looking for is not available"}, status: 404}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from ActionController::RoutingError, :with => :render_not_found
  rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found

  def render_not_found(e)
    respond_to do |format|
      format.html { render template: "errors/404", status: 404}
      format.json { render json: {messages: "The resource you're looking for is not available"}, status: 404}
    end
  end

  def raise_not_found!
    raise ActionController::RoutingError.new("No route matches #{params[:unmatched_route]}")
  end

  private
    def configure_permitted_parameters
      #devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
      #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.page(page).per(per_page)
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:first_name, :last_name, :address, :phone, :sex, :born, :front_title, :back_title, :role)
    end

    def page
      params[:page] ? params[:page] : 1
    end

    def per_page
      params[:per_page] ? params[:per_page] : 10
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Medical
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |key, value|
      %p{:class => key}
        = value
    = yield

app/views/layouts/session.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Medical
    = stylesheet_link_tag    'session', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'session', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #flash
      - flash.each do |key, value|
        %div{ class: "alert alert-#{key}", style: "display: none;"}
          %p= value
    = yield

app/views/staffs/_form.html.haml
= form_for @staff do |f|
  - if @staff.errors.any?
    #error_explanation
      %h2= "#{pluralize(@staff.errors.count, "error")} prohibited this staff from being saved:"
      %ul
        - @staff.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :address
    = f.text_area :address
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :sex
    = f.text_field :sex
  .field
    = f.label :born
    = f.date_select :born
  .field
    = f.label :front_title
    = f.text_field :front_title
  .field
    = f.label :back_title
    = f.text_field :back_title
  .field
    = f.label :role
    = f.text_field :role
  .actions
    = f.submit 'Save'

app/views/staffs/edit.html.haml
%h1 Editing staff

= render 'form'

= link_to 'Show', @staff
\|
= link_to 'Back', staffs_path

app/views/staffs/index.html.haml
%h1 Listing staffs

%table
  %thead
    %tr
      %th Full name
      %th Address
      %th Phone
      %th Sex
      %th Born
      %th Role
      %th Action
      %th
      %th

  %tbody
    - @staffs.each do |staff|
      %tr
        %td= staff.display_name
        %td= staff.address
        %td= staff.phone
        %td= staff.sex
        %td= staff.born
        %td= staff.role
        %td
          = link_to 'Detail', staff
          = link_to 'Edit', edit_staff_path(staff)
          = link_to 'Delete', staff, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Staff', new_staff_path

app/views/staffs/new.html.haml
%h1 New staff

= render 'form'

= link_to 'Back', staffs_path

app/views/staffs/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @staff.first_name
%p
  %b Last name:
  = @staff.last_name
%p
  %b Address:
  = @staff.address
%p
  %b Phone:
  = @staff.phone
%p
  %b Sex:
  = @staff.sex
%p
  %b Born:
  = @staff.born
%p
  %b Front title:
  = @staff.front_title
%p
  %b Back title:
  = @staff.back_title
%p
  %b Role:
  = @staff.role

= link_to 'Edit', edit_staff_path(@staff)
\|
= link_to 'Back', staffs_path

app/views/statics/landing.html.haml
%h1 Statics#landing
%p Find me in app/views/statics/landing.html.haml